//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapSoapCardWriter.GUI.SapNakResponseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC")]
    public interface Z_CRM_NEBIH_CARD_WRSUCC {
        
        // CODEGEN: Generating message contract since the operation Z_CRM_NEBIH_CARD_WRSUCC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NEBIH_CARD_WRSUCC:Z_CRM_NEBIH_CARD_W" +
            "RSUCCRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1 Z_CRM_NEBIH_CARD_WRSUCC(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NEBIH_CARD_WRSUCC:Z_CRM_NEBIH_CARD_W" +
            "RSUCCRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1> Z_CRM_NEBIH_CARD_WRSUCCAsync(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NEBIH_CARD_WRSUCC_DATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cARD_IDField;
        
        private string pASSWDField;
        
        private string uNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CARD_ID {
            get {
                return this.cARD_IDField;
            }
            set {
                this.cARD_IDField = value;
                this.RaisePropertyChanged("CARD_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PASSWD {
            get {
                return this.pASSWDField;
            }
            set {
                this.pASSWDField = value;
                this.RaisePropertyChanged("PASSWD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
                this.RaisePropertyChanged("UNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NEBIH_CARD_WRSUCCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eRRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NEBIH_CARD_WRSUCCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC_DATA Z_CRM_NEBIH_CARD_WRSUCC;
        
        public Z_CRM_NEBIH_CARD_WRSUCCRequest() {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCRequest(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC_DATA Z_CRM_NEBIH_CARD_WRSUCC) {
            this.Z_CRM_NEBIH_CARD_WRSUCC = Z_CRM_NEBIH_CARD_WRSUCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NEBIH_CARD_WRSUCCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse Z_CRM_NEBIH_CARD_WRSUCCResponse;
        
        public Z_CRM_NEBIH_CARD_WRSUCCResponse1() {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCResponse1(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse Z_CRM_NEBIH_CARD_WRSUCCResponse) {
            this.Z_CRM_NEBIH_CARD_WRSUCCResponse = Z_CRM_NEBIH_CARD_WRSUCCResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CRM_NEBIH_CARD_WRSUCCChannel : SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CRM_NEBIH_CARD_WRSUCCClient : System.ServiceModel.ClientBase<SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC>, SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC {
        
        public Z_CRM_NEBIH_CARD_WRSUCCClient() {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NEBIH_CARD_WRSUCCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1 SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC.Z_CRM_NEBIH_CARD_WRSUCC(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest request) {
            return base.Channel.Z_CRM_NEBIH_CARD_WRSUCC(request);
        }
        
        public SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse Z_CRM_NEBIH_CARD_WRSUCC(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC_DATA Z_CRM_NEBIH_CARD_WRSUCC1) {
            SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest inValue = new SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest();
            inValue.Z_CRM_NEBIH_CARD_WRSUCC = Z_CRM_NEBIH_CARD_WRSUCC1;
            SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1 retVal = ((SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC)(this)).Z_CRM_NEBIH_CARD_WRSUCC(inValue);
            return retVal.Z_CRM_NEBIH_CARD_WRSUCCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1> SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC.Z_CRM_NEBIH_CARD_WRSUCCAsync(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest request) {
            return base.Channel.Z_CRM_NEBIH_CARD_WRSUCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCResponse1> Z_CRM_NEBIH_CARD_WRSUCCAsync(SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC_DATA Z_CRM_NEBIH_CARD_WRSUCC) {
            SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest inValue = new SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCCRequest();
            inValue.Z_CRM_NEBIH_CARD_WRSUCC = Z_CRM_NEBIH_CARD_WRSUCC;
            return ((SapSoapCardWriter.GUI.SapNakResponseService.Z_CRM_NEBIH_CARD_WRSUCC)(this)).Z_CRM_NEBIH_CARD_WRSUCCAsync(inValue);
        }
    }
}
