//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapSoapCardWriter.GUI.SapNakAuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH")]
    public interface Z_CRM_NEBIH_CARD_AUTH {
        
        // CODEGEN: Generating message contract since the operation Z_CRM_NEBIH_CARD_AUTH is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NEBIH_CARD_AUTH:Z_CRM_NEBIH_CARD_AUT" +
            "HRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1 Z_CRM_NEBIH_CARD_AUTH(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NEBIH_CARD_AUTH:Z_CRM_NEBIH_CARD_AUT" +
            "HRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1> Z_CRM_NEBIH_CARD_AUTHAsync(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NEBIH_CARD_AUTH_DATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pASSWDField;
        
        private string uNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PASSWD {
            get {
                return this.pASSWDField;
            }
            set {
                this.pASSWDField = value;
                this.RaisePropertyChanged("PASSWD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
                this.RaisePropertyChanged("UNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NEBIH_CARD_AUTHResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eRRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NEBIH_CARD_AUTHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH_DATA Z_CRM_NEBIH_CARD_AUTH;
        
        public Z_CRM_NEBIH_CARD_AUTHRequest() {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHRequest(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH_DATA Z_CRM_NEBIH_CARD_AUTH) {
            this.Z_CRM_NEBIH_CARD_AUTH = Z_CRM_NEBIH_CARD_AUTH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NEBIH_CARD_AUTHResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse Z_CRM_NEBIH_CARD_AUTHResponse;
        
        public Z_CRM_NEBIH_CARD_AUTHResponse1() {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHResponse1(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse Z_CRM_NEBIH_CARD_AUTHResponse) {
            this.Z_CRM_NEBIH_CARD_AUTHResponse = Z_CRM_NEBIH_CARD_AUTHResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CRM_NEBIH_CARD_AUTHChannel : SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CRM_NEBIH_CARD_AUTHClient : System.ServiceModel.ClientBase<SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH>, SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH {
        
        public Z_CRM_NEBIH_CARD_AUTHClient() {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NEBIH_CARD_AUTHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1 SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH.Z_CRM_NEBIH_CARD_AUTH(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest request) {
            return base.Channel.Z_CRM_NEBIH_CARD_AUTH(request);
        }
        
        public SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse Z_CRM_NEBIH_CARD_AUTH(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH_DATA Z_CRM_NEBIH_CARD_AUTH1) {
            SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest inValue = new SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest();
            inValue.Z_CRM_NEBIH_CARD_AUTH = Z_CRM_NEBIH_CARD_AUTH1;
            SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1 retVal = ((SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH)(this)).Z_CRM_NEBIH_CARD_AUTH(inValue);
            return retVal.Z_CRM_NEBIH_CARD_AUTHResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1> SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH.Z_CRM_NEBIH_CARD_AUTHAsync(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest request) {
            return base.Channel.Z_CRM_NEBIH_CARD_AUTHAsync(request);
        }
        
        public System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHResponse1> Z_CRM_NEBIH_CARD_AUTHAsync(SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH_DATA Z_CRM_NEBIH_CARD_AUTH) {
            SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest inValue = new SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTHRequest();
            inValue.Z_CRM_NEBIH_CARD_AUTH = Z_CRM_NEBIH_CARD_AUTH;
            return ((SapSoapCardWriter.GUI.SapNakAuthService.Z_CRM_NEBIH_CARD_AUTH)(this)).Z_CRM_NEBIH_CARD_AUTHAsync(inValue);
        }
    }
}
