//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapSoapCardWriter.GUI.SapNakRegisterCardToEvent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARD")]
    public interface IZ_CRM_NAK_EVENT_SELECT_CARD {
        
        // CODEGEN: Generating message contract since the operation Z_CRM_NAK_EVENT_SELECT_CARD is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NAK_EVENT_SELECT_CARD:Z_CRM_NAK_EVEN" +
            "T_SELECT_CARDRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1 Z_CRM_NAK_EVENT_SELECT_CARD(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NAK_EVENT_SELECT_CARD:Z_CRM_NAK_EVEN" +
            "T_SELECT_CARDRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1> Z_CRM_NAK_EVENT_SELECT_CARDAsync(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NAK_EVENT_SELECT_CARD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cARD_IDField;
        
        private byte[] eVENT_GUIDField;
        
        private string pASSWDField;
        
        private string uNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CARD_ID {
            get {
                return this.cARD_IDField;
            }
            set {
                this.cARD_IDField = value;
                this.RaisePropertyChanged("CARD_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] EVENT_GUID {
            get {
                return this.eVENT_GUIDField;
            }
            set {
                this.eVENT_GUIDField = value;
                this.RaisePropertyChanged("EVENT_GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PASSWD {
            get {
                return this.pASSWDField;
            }
            set {
                this.pASSWDField = value;
                this.RaisePropertyChanged("PASSWD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
                this.RaisePropertyChanged("UNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRMS_NAK_MASS_EVENT_MSG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NAK_EVENT_SELECT_CARDResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCRMS_NAK_MASS_EVENT_MSG[] mESSAGESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRMS_NAK_MASS_EVENT_MSG[] MESSAGES {
            get {
                return this.mESSAGESField;
            }
            set {
                this.mESSAGESField = value;
                this.RaisePropertyChanged("MESSAGES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NAK_EVENT_SELECT_CARDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARD Z_CRM_NAK_EVENT_SELECT_CARD;
        
        public Z_CRM_NAK_EVENT_SELECT_CARDRequest() {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDRequest(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARD Z_CRM_NAK_EVENT_SELECT_CARD) {
            this.Z_CRM_NAK_EVENT_SELECT_CARD = Z_CRM_NAK_EVENT_SELECT_CARD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NAK_EVENT_SELECT_CARDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse Z_CRM_NAK_EVENT_SELECT_CARDResponse;
        
        public Z_CRM_NAK_EVENT_SELECT_CARDResponse1() {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDResponse1(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse Z_CRM_NAK_EVENT_SELECT_CARDResponse) {
            this.Z_CRM_NAK_EVENT_SELECT_CARDResponse = Z_CRM_NAK_EVENT_SELECT_CARDResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CRM_NAK_EVENT_SELECT_CARDChannel : IZ_CRM_NAK_EVENT_SELECT_CARD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CRM_NAK_EVENT_SELECT_CARDClient : System.ServiceModel.ClientBase<IZ_CRM_NAK_EVENT_SELECT_CARD>, IZ_CRM_NAK_EVENT_SELECT_CARD {
        
        public Z_CRM_NAK_EVENT_SELECT_CARDClient() {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NAK_EVENT_SELECT_CARDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1 IZ_CRM_NAK_EVENT_SELECT_CARD.Z_CRM_NAK_EVENT_SELECT_CARD(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest request) {
            return base.Channel.Z_CRM_NAK_EVENT_SELECT_CARD(request);
        }
        
        public SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse Z_CRM_NAK_EVENT_SELECT_CARD(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARD Z_CRM_NAK_EVENT_SELECT_CARD1) {
            SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest inValue = new SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest();
            inValue.Z_CRM_NAK_EVENT_SELECT_CARD = Z_CRM_NAK_EVENT_SELECT_CARD1;
            SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1 retVal = ((IZ_CRM_NAK_EVENT_SELECT_CARD)(this)).Z_CRM_NAK_EVENT_SELECT_CARD(inValue);
            return retVal.Z_CRM_NAK_EVENT_SELECT_CARDResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1> IZ_CRM_NAK_EVENT_SELECT_CARD.Z_CRM_NAK_EVENT_SELECT_CARDAsync(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest request) {
            return base.Channel.Z_CRM_NAK_EVENT_SELECT_CARDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDResponse1> Z_CRM_NAK_EVENT_SELECT_CARDAsync(SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARD Z_CRM_NAK_EVENT_SELECT_CARD) {
            SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest inValue = new SapSoapCardWriter.GUI.SapNakRegisterCardToEvent.Z_CRM_NAK_EVENT_SELECT_CARDRequest();
            inValue.Z_CRM_NAK_EVENT_SELECT_CARD = Z_CRM_NAK_EVENT_SELECT_CARD;
            return ((IZ_CRM_NAK_EVENT_SELECT_CARD)(this)).Z_CRM_NAK_EVENT_SELECT_CARDAsync(inValue);
        }
    }
}
