//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapSoapCardWriter.GUI.SapNakEventListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDEN")]
    public interface IZ_CRM_NAK_EVENTS_LIST_CARDIDEN {
        
        // CODEGEN: Generating message contract since the operation Z_CRM_NAK_EVENTS_LIST_CARDIDEN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NAK_EVENTS_LIST_CARDIDEN:Z_CRM_NAK_E" +
            "VENTS_LIST_CARDIDENRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1 Z_CRM_NAK_EVENTS_LIST_CARDIDEN(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:Z_CRM_NAK_EVENTS_LIST_CARDIDEN:Z_CRM_NAK_E" +
            "VENTS_LIST_CARDIDENRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1> Z_CRM_NAK_EVENTS_LIST_CARDIDENAsync(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NAK_EVENTS_LIST_CARDIDEN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pASSWDField;
        
        private string uNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PASSWD {
            get {
                return this.pASSWDField;
            }
            set {
                this.pASSWDField = value;
                this.RaisePropertyChanged("PASSWD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UNAME {
            get {
                return this.uNAMEField;
            }
            set {
                this.uNAMEField = value;
                this.RaisePropertyChanged("UNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRMS_NAK_MASS_EVENT_LIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] gUIDField;
        
        private string oBJECT_IDField;
        
        private string nAMEField;
        
        private string lOCATIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OBJECT_ID {
            get {
                return this.oBJECT_IDField;
            }
            set {
                this.oBJECT_IDField = value;
                this.RaisePropertyChanged("OBJECT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOCATION {
            get {
                return this.lOCATIONField;
            }
            set {
                this.lOCATIONField = value;
                this.RaisePropertyChanged("LOCATION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eRRORField;
        
        private ZCRMS_NAK_MASS_EVENT_LIST[] eVENTS_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
                this.RaisePropertyChanged("ERROR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRMS_NAK_MASS_EVENT_LIST[] EVENTS_LIST {
            get {
                return this.eVENTS_LISTField;
            }
            set {
                this.eVENTS_LISTField = value;
                this.RaisePropertyChanged("EVENTS_LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public Z_CRM_NAK_EVENTS_LIST_CARDIDEN Z_CRM_NAK_EVENTS_LIST_CARDIDEN;
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest() {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest(Z_CRM_NAK_EVENTS_LIST_CARDIDEN Z_CRM_NAK_EVENTS_LIST_CARDIDEN) {
            this.Z_CRM_NAK_EVENTS_LIST_CARDIDEN = Z_CRM_NAK_EVENTS_LIST_CARDIDEN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse;
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1() {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse) {
            this.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse = Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CRM_NAK_EVENTS_LIST_CARDIDENChannel : IZ_CRM_NAK_EVENTS_LIST_CARDIDEN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CRM_NAK_EVENTS_LIST_CARDIDENClient : System.ServiceModel.ClientBase<IZ_CRM_NAK_EVENTS_LIST_CARDIDEN>, IZ_CRM_NAK_EVENTS_LIST_CARDIDEN {
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENClient() {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CRM_NAK_EVENTS_LIST_CARDIDENClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1 IZ_CRM_NAK_EVENTS_LIST_CARDIDEN.Z_CRM_NAK_EVENTS_LIST_CARDIDEN(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest request) {
            return base.Channel.Z_CRM_NAK_EVENTS_LIST_CARDIDEN(request);
        }
        
        public SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse Z_CRM_NAK_EVENTS_LIST_CARDIDEN(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDEN Z_CRM_NAK_EVENTS_LIST_CARDIDEN1) {
            SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest inValue = new SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest();
            inValue.Z_CRM_NAK_EVENTS_LIST_CARDIDEN = Z_CRM_NAK_EVENTS_LIST_CARDIDEN1;
            SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1 retVal = ((IZ_CRM_NAK_EVENTS_LIST_CARDIDEN)(this)).Z_CRM_NAK_EVENTS_LIST_CARDIDEN(inValue);
            return retVal.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1> IZ_CRM_NAK_EVENTS_LIST_CARDIDEN.Z_CRM_NAK_EVENTS_LIST_CARDIDENAsync(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest request) {
            return base.Channel.Z_CRM_NAK_EVENTS_LIST_CARDIDENAsync(request);
        }
        
        public System.Threading.Tasks.Task<SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENResponse1> Z_CRM_NAK_EVENTS_LIST_CARDIDENAsync(SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDEN Z_CRM_NAK_EVENTS_LIST_CARDIDEN) {
            SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest inValue = new SapSoapCardWriter.GUI.SapNakEventListService.Z_CRM_NAK_EVENTS_LIST_CARDIDENRequest();
            inValue.Z_CRM_NAK_EVENTS_LIST_CARDIDEN = Z_CRM_NAK_EVENTS_LIST_CARDIDEN;
            return ((IZ_CRM_NAK_EVENTS_LIST_CARDIDEN)(this)).Z_CRM_NAK_EVENTS_LIST_CARDIDENAsync(inValue);
        }
    }
}
